// Tire Database
// Each tire has physics characteristics that will be used to generate unique LUT files

const TIRE_DATABASE = {
    lowHP: [
        {
            id: 101,
            name: "GT Radial SX2 (Hard)",
            shortName: "GTH",
            tier: "lowHP",
            compound: "hard"
        },
        {
            id: 102,
            name: "GT Radial SX2 (Medium)",
            shortName: "GTM",
            tier: "lowHP",
            compound: "medium"
        },
        {
            id: 103,
            name: "GT Radial SX2 (Soft)",
            shortName: "GTS",
            tier: "lowHP",
            compound: "soft"
        }
    ],
    street: [
        {
            id: 1,
            name: "Ironman iMove Gen 2",
            shortName: "IRON",
            treadwear: 420,
            traction: "A",
            gripMultiplier: 0.82,
            peakSlipAngle: 9.2,
            combinedFactor: 2.40,
            combinedFactor1: 0.40,
            satMult: 0.70,
            camberGain: 0.070,
            flexGain: -0.018,
            falloffLevel: 0.880,
            falloffSpeed: 15.0,
            pressureIdeal: 35.0,
            coldGrip: 0.92,
            optimalTempLow: 20,
            optimalTempHigh: 110,
            overheatDropoff: 0.92,
            heatSpeed: 1.5,
            camberPeakAngle: -2,
            camberPeakValue: 1.040,
            camberSensitivity: "minimal",
            wearLife: 5.0,
            wearKm: 16.0,
        },
        {
            id: 2,
            name: "Nitto NT555RII",
            shortName: "N555",
            treadwear: 200,
            traction: "AA",
            gripMultiplier: 0.84,
            peakSlipAngle: 8.8,
            combinedFactor: 2.25,
            combinedFactor1: 0.38,
            satMult: 0.73,
            camberGain: 0.080,
            flexGain: -0.015,
            falloffLevel: 0.820,
            falloffSpeed: 13.5,
            pressureIdeal: 33.0,
            coldGrip: 0.94,
            optimalTempLow: 30,
            optimalTempHigh: 100,
            overheatDropoff: 0.90,
            heatSpeed: 0.9,
            camberPeakAngle: -2.5,
            camberPeakValue: 1.055,
            camberSensitivity: "low",
            wearLife: 5.5,
            wearKm: 18.0,
        },
        {
            id: 3,
            name: "Accelera 351 Sport GD",
            shortName: "A351",
            treadwear: 300,
            traction: "A",
            gripMultiplier: 0.86,
            peakSlipAngle: 8.5,
            combinedFactor: 2.30,
            combinedFactor1: 0.38,
            satMult: 0.75,
            camberGain: 0.075,
            flexGain: -0.016,
            falloffLevel: 0.850,
            falloffSpeed: 14.0,
            pressureIdeal: 34.0,
            coldGrip: 0.92,
            optimalTempLow: 40,
            optimalTempHigh: 100,
            overheatDropoff: 0.91,
            heatSpeed: 1.3,
            camberPeakAngle: -3,
            camberPeakValue: 1.060,
            camberSensitivity: "low",
            wearLife: 3.6,
            wearKm: 13.0,
        },
        {
            id: 4,
            name: "Accelera 651 Sport",
            shortName: "A651",
            treadwear: 140,
            traction: "AA",
            gripMultiplier: 0.88,
            peakSlipAngle: 7.8,
            combinedFactor: 2.15,
            combinedFactor1: 0.35,
            satMult: 0.78,
            camberGain: 0.095,
            flexGain: -0.012,
            falloffLevel: 0.760,
            falloffSpeed: 12.0,
            pressureIdeal: 32.0,
            coldGrip: 0.88,
            optimalTempLow: 55,
            optimalTempHigh: 95,
            overheatDropoff: 0.89,
            heatSpeed: 1.1,
            camberPeakAngle: -3.5,
            camberPeakValue: 1.090,
            camberSensitivity: "moderate",
            wearLife: 2.4,
            wearKm: 11.8,
        },
        {
            id: 5,
            name: "Kenda Vezda KR20A",
            shortName: "KR20",
            treadwear: 200,
            traction: "A",
            // Physics characteristics
            gripMultiplier: 0.90,           // Base: 1.0 for reference
            peakSlipAngle: 7.5,             // Degrees
            combinedFactor: 2.05,
            combinedFactor1: 0.33,
            satMult: 0.80,
            camberGain: 0.105,
            flexGain: -0.011,
            falloffLevel: 0.730,
            falloffSpeed: 11.0,
            pressureIdeal: 31.0,
            // Thermal characteristics
            coldGrip: 0.90,                 // Multiplier at 0°C
            optimalTempLow: 60,
            optimalTempHigh: 90,
            overheatDropoff: 0.80,          // Multiplier at very high temp
            heatSpeed: 1.0,                 // Heat buildup rate multiplier
            // Camber curve
            camberPeakAngle: -4,
            camberPeakValue: 1.110,
            camberSensitivity: "moderate",
            // Wear
            wearLife: 2.6,                  // Multiplier vs reference
            wearKm: 11.4,                    // Distance before major dropoff
        },
        {
            id: 6,
            name: "Toyo Proxes R888R",
            shortName: "R888",
            treadwear: 100,
            traction: "AA",
            gripMultiplier: 0.92,
            peakSlipAngle: 6.5,
            combinedFactor: 1.88,
            combinedFactor1: 0.31,
            satMult: 0.83,
            camberGain: 0.125,
            flexGain: -0.008,
            falloffLevel: 0.680,
            falloffSpeed: 9.5,
            pressureIdeal: 30.0,
            coldGrip: 0.83,
            optimalTempLow: 75,
            optimalTempHigh: 105,
            overheatDropoff: 0.87,
            heatSpeed: 0.9,
            camberPeakAngle: -5,
            camberPeakValue: 1.145,
            camberSensitivity: "high",
            wearLife: 3.0,
            wearKm: 12.4,
        },
        {
            id: 7,
            name: "Nankang NS-2R",
            shortName: "NS2R",
            treadwear: 120,
            traction: "AA",
            gripMultiplier: 0.93,
            peakSlipAngle: 7.3,
            combinedFactor: 2.08,
            combinedFactor1: 0.34,
            satMult: 0.85,
            camberGain: 0.100,
            flexGain: -0.011,
            falloffLevel: 0.740,
            falloffSpeed: 11.5,
            pressureIdeal: 31.5,
            coldGrip: 0.84,
            optimalTempLow: 55,
            optimalTempHigh: 95,
            overheatDropoff: 0.86,
            heatSpeed: 1.0,
            camberPeakAngle: -3.5,
            camberPeakValue: 1.100,
            camberSensitivity: "moderate",
            wearLife: 2.4,
            wearKm: 11.6,
        },
        {
            id: 8,
            name: "GT Radial Champiro SX2 RS",
            shortName: "SX2",
            treadwear: 140,
            traction: "AA",
            gripMultiplier: 0.95,           // Reference tire
            peakSlipAngle: 7.50,
            combinedFactor: 2.05,
            combinedFactor1: 0.33,
            satMult: 0.88,
            camberGain: 0.105,
            flexGain: -0.011,
            falloffLevel: 0.730,
            falloffSpeed: 11.0,
            pressureIdeal: 31.0,
            coldGrip: 0.89,
            optimalTempLow: 60,
            optimalTempHigh: 95,
            overheatDropoff: 0.85,
            heatSpeed: 1.0,
            camberPeakAngle: -4,
            camberPeakValue: 1.110,
            camberSensitivity: "moderate",
            wearLife: 2.8,
            wearKm: 12.0,
        },
        {
            id: 9,
            name: "Federal 595RS-RR",
            shortName: "F595",
            treadwear: 200,
            traction: "AA",
            gripMultiplier: 0.96,
            peakSlipAngle: 7.0,
            combinedFactor: 2.00,
            combinedFactor1: 0.32,
            satMult: 0.90,
            camberGain: 0.110,
            flexGain: -0.010,
            falloffLevel: 0.710,
            falloffSpeed: 10.5,
            pressureIdeal: 31.0,
            coldGrip: 0.87,
            optimalTempLow: 70,
            optimalTempHigh: 92,
            overheatDropoff: 0.85,
            heatSpeed: 1.3,
            camberPeakAngle: -4,
            camberPeakValue: 1.115,
            camberSensitivity: "high",
            wearLife: 2.0,
            wearKm: 11.0,
        },
        {
            id: 10,
            name: "Valino Pergea 08RS",
            shortName: "VP08",
            treadwear: 200,
            traction: "A",
            gripMultiplier: 0.97,
            peakSlipAngle: 6.8,
            combinedFactor: 1.95,
            combinedFactor1: 0.32,
            satMult: 0.93,
            camberGain: 0.120,
            flexGain: -0.009,
            falloffLevel: 0.700,
            falloffSpeed: 10.0,
            pressureIdeal: 31.0,
            coldGrip: 0.86,
            optimalTempLow: 70,
            optimalTempHigh: 100,
            overheatDropoff: 0.84,
            heatSpeed: 1.2,
            camberPeakAngle: -4.5,
            camberPeakValue: 1.130,
            camberSensitivity: "high",
            wearLife: 1.6,
            wearKm: 9.6,
        },
    ],
    competition: [
        {
            id: 11,
            name: "Nitto NT555 G2",
            shortName: "N555G2",
            treadwear: 340,
            traction: "AA",
            gripMultiplier: 0.88,
            peakSlipAngle: 8.0,
            combinedFactor: 2.18,
            combinedFactor1: 0.36,
            satMult: 0.80,
            camberGain: 0.090,
            flexGain: -0.013,
            falloffLevel: 0.780,
            falloffSpeed: 12.5,
            pressureIdeal: 32.5,
            coldGrip: 0.93,
            optimalTempLow: 35,
            optimalTempHigh: 100,
            overheatDropoff: 0.88,
            heatSpeed: 0.65,
            camberPeakAngle: -3,
            camberPeakValue: 1.075,
            camberSensitivity: "low",
            wearLife: 3.4,
            wearKm: 16.0,
        },
        {
            id: 12,
            name: "Falken Azenis RT615K+",
            shortName: "RT615",
            treadwear: 200,
            traction: "AA",
            gripMultiplier: 0.91,
            peakSlipAngle: 7.2,
            combinedFactor: 2.02,
            combinedFactor1: 0.33,
            satMult: 0.83,
            camberGain: 0.108,
            flexGain: -0.010,
            falloffLevel: 0.720,
            falloffSpeed: 11.0,
            pressureIdeal: 31.0,
            coldGrip: 0.88,
            optimalTempLow: 60,
            optimalTempHigh: 94,
            overheatDropoff: 0.86,
            heatSpeed: 0.5,
            camberPeakAngle: -4,
            camberPeakValue: 1.112,
            camberSensitivity: "moderate",
            wearLife: 2.6,
            wearKm: 11.8,
        },
        {
            id: 13,
            name: "Kumho Ecsta V730",
            shortName: "V730",
            treadwear: 60,
            traction: "AA",
            gripMultiplier: 0.93,
            peakSlipAngle: 6.6,
            combinedFactor: 1.90,
            combinedFactor1: 0.30,
            satMult: 0.85,
            camberGain: 0.128,
            flexGain: -0.008,
            falloffLevel: 0.680,
            falloffSpeed: 9.8,
            pressureIdeal: 30.0,
            coldGrip: 0.86,
            optimalTempLow: 68,
            optimalTempHigh: 96,
            overheatDropoff: 0.85,
            heatSpeed: 0.55,
            camberPeakAngle: -5,
            camberPeakValue: 1.138,
            camberSensitivity: "high",
            wearLife: 2.0,
            wearKm: 11.2,
        },
        {
            id: 14,
            name: "GT Radial SX2 RS (Pro)",
            shortName: "SX2P",
            treadwear: 60,
            traction: "AA",
            gripMultiplier: 0.95,
            peakSlipAngle: 7.2,
            combinedFactor: 1.98,
            combinedFactor1: 0.32,
            satMult: 0.88,
            camberGain: 0.115,
            flexGain: -0.010,
            falloffLevel: 0.710,
            falloffSpeed: 10.5,
            pressureIdeal: 30.5,
            coldGrip: 0.87,
            optimalTempLow: 65,
            optimalTempHigh: 98,
            overheatDropoff: 0.84,
            heatSpeed: 0.55,
            camberPeakAngle: -4.5,
            camberPeakValue: 1.125,
            camberSensitivity: "high",
            wearLife: 1.8,
            wearKm: 10.4,
        },
        {
            id: 15,
            name: "Bridgestone Potenza RE-71RS",
            shortName: "RE71",
            treadwear: 200,
            traction: "AA",
            gripMultiplier: 0.96,
            peakSlipAngle: 6.3,
            combinedFactor: 1.85,
            combinedFactor1: 0.30,
            satMult: 0.90,
            camberGain: 0.132,
            flexGain: -0.008,
            falloffLevel: 0.670,
            falloffSpeed: 9.5,
            pressureIdeal: 30.0,
            coldGrip: 0.84,
            optimalTempLow: 72,
            optimalTempHigh: 98,
            overheatDropoff: 0.84,
            heatSpeed: 0.6,
            camberPeakAngle: -5.5,
            camberPeakValue: 1.150,
            camberSensitivity: "very high",
            wearLife: 2.0,
            wearKm: 11.0,
        },
        {
            id: 16,
            name: "Federal RS-Pro",
            shortName: "FPRO",
            treadwear: 140,
            traction: "AA",
            gripMultiplier: 0.98,
            peakSlipAngle: 6.7,
            combinedFactor: 1.93,
            combinedFactor1: 0.31,
            satMult: 0.93,
            camberGain: 0.123,
            flexGain: -0.009,
            falloffLevel: 0.685,
            falloffSpeed: 10.2,
            pressureIdeal: 30.5,
            coldGrip: 0.86,
            optimalTempLow: 72,
            optimalTempHigh: 97,
            overheatDropoff: 0.83,
            heatSpeed: 0.65,
            camberPeakAngle: -5,
            camberPeakValue: 1.135,
            camberSensitivity: "very high",
            wearLife: 1.6,
            wearKm: 10.0,
        },
        {
            id: 17,
            name: "Kenda Competition",
            shortName: "KPRO",
            treadwear: 80,
            traction: "AA",
            gripMultiplier: 1.00,
            peakSlipAngle: 6.8,
            combinedFactor: 1.92,
            combinedFactor1: 0.31,
            satMult: 0.95,
            camberGain: 0.125,
            flexGain: -0.009,
            falloffLevel: 0.690,
            falloffSpeed: 10.0,
            pressureIdeal: 30.0,
            coldGrip: 0.85,
            optimalTempLow: 70,
            optimalTempHigh: 105,
            overheatDropoff: 0.82,
            heatSpeed: 0.6,
            camberPeakAngle: -5,
            camberPeakValue: 1.140,
            camberSensitivity: "high",
            wearLife: 1.5,
            wearKm: 9.8,
        },
    ]
};
